### ISSUE TITLE
KG2.8.4pre Edge Doesn't Have qualified_object_direction

### ISSUE THREAD

**Issue by ecwood** [RTXteam/RTX-KG2#339]
From @saramsey:

> Erica, do you know why the following triple in KG2.8.4pre doesn't have any qualified_object_direction  property?

```
match (n {id: 'CHEMBL.COMPOUND:CHEMBL254219'})-[r]->(m {id: 'NCBIGene:477'}) return r;
```
returns
```
{
  "negated": "False",
  "primary_knowledge_source": "infores:dgidb",
  "qualified_object_aspect": "activity",
  "qualified_predicate": "biolink:causes",
  "relation_label": "inhibitor",
  "subject": "CHEMBL.COMPOUND:CHEMBL254219",
  "source_predicate": "DGIdb:inhibitor",
  "update_date": "2022-Feb",
  "predicate": "biolink:affects",
  "domain_range_exclusion": "False",
  "publications_info": "{}",
  "predicate_label": "inhibitor",
  "id": "CHEMBL.COMPOUND:CHEMBL254219---DGIdb:inhibitor---biolink:causes---activity---None---NCBIGene:477---DGIdb:",
  "object": "NCBIGene:477"
} 
```

I note that the relevant block of predicate-remap.yaml does show a qualified direction of decreased:
```
DGIdb:inhibitor:
  operation: keep
  core_predicate: biolink:affects
  qualified_predicate: biolink:causes
  qualifiers:
    - object_aspect: activity
    - object_direction: decreased
```

There are other edges with this property.
