### ISSUE TITLE
DRUGBANK:drug-interaction is incorrectly being mapped to biolink:physically_interacts_with

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#340]
This issue was brought to my attention by [NCATSTranslator/Feedback issue 415](https://github.com/NCATSTranslator/Feedback/issues/415). 

Confirmed, in Neo4j endpoint `kg2endpoint-kg2-8-4.rtx.ai`, the Cypher query
```
match (n {id: 'DRUGBANK:DB00393'})-[r]-(m {id: 'DRUGBANK:DB04695'}) return r;
```
returns the JSON result
```
{   "predicate": "biolink:physically_interacts_with",   "domain_range_exclusion": "False",   "negated": "False",   "primary_knowledge_source": "infores:drugbank",   "relation_label": "drug_interaction",   "publications_info": "{'sentence': 'The risk or severity of QTc prolongation can be increased when Farnesyl thiopyrophosphate is combined with Nimodipine.'}",   "subject": "DRUGBANK:DB04695",   "source_predicate": "DRUGBANK:drug-interaction",   "predicate_label": "drug-interaction",   "id": "DRUGBANK:DB04695---DRUGBANK:drug-interaction---None---None---None---DRUGBANK:DB00393---identifiers_org_registry:drugbank",   "object": "DRUGBANK:DB00393" }
--
{   "predicate": "biolink:physically_interacts_with",   "domain_range_exclusion": "False",   "negated": "False",   "primary_knowledge_source": "infores:drugbank",   "relation_label": "drug_interaction",   "publications_info": "{'sentence': 'The risk or severity of QTc prolongation can be increased when Farnesyl thiopyrophosphate is combined with Nimodipine.'}",   "subject": "DRUGBANK:DB00393",   "source_predicate": "DRUGBANK:drug-interaction",   "predicate_label": "drug-interaction",   "id": "DRUGBANK:DB00393---DRUGBANK:drug-interaction---None---None---None---DRUGBANK:DB04695---identifiers_org_registry:drugbank",   "object": "DRUGBANK:DB04695" }
```
which seems like it should not be the correct mapping for a drug interaction.

**Comment by saramsey** [comment]
So the issue here is that there seems to be no appropriate Biolink predicate to represent this interaction. In the current `biolink-model.yaml` file, `DRUGBANK:interacts-with` is mapped to `biolink:physically_interacts_with`, as shown here:
https://github.com/biolink/biolink-model/blob/450cb767f03da6f171b20809dd4a45aed20bb6a4/biolink-model.yaml#L2314-L2341
I agree, `biolink:physically_interacts_with` is wrong. But so it `biolink:genetically_interacts_with`. We can't use `biolink:interacts_with` because it is a mixin. The only other option is `biolink:related_to` which is rather uninformative. So yes, on one level this is a problem in KG2pre, but on the other hand, we're blocking on clarification from the Biolink team about how to handle this.

**Comment by saramsey** [comment]
This issue is blocking on [biolink/biolink-model issue 1371](https://github.com/biolink/biolink-model/issues/1371).

**Comment by saramsey** [comment]
Apparently, `DRUGBANK:interacts-with` at some point in the last 18 months got changed to `DRUGBANK:drug-interaction`:
```
{
  "knowledge_level": "knowledge_assertion",
  "negated": "False",
  "primary_knowledge_source": "infores:drugbank",
  "relation_label": "drug_interaction",
  "subject": "DRUGBANK:DB04695",
  "source_predicate": "DRUGBANK:drug-interaction",
  "agent_type": "manual_agent",
  "predicate": "biolink:interacts_with",
  "domain_range_exclusion": "False",
  "publications_info": "{'sentence': 'The risk or severity of QTc prolongation can be increased when Farnesyl thiopyrophosphate is combined with Nimodipine.'}",
  "predicate_label": "drug-interaction",
  "id": "DRUGBANK:DB04695---DRUGBANK:drug-interaction---None---None---None---DRUGBANK:DB00393---identifiers_org_registry:drugbank",
  "object": "DRUGBANK:DB00393"
}

{
  "knowledge_level": "knowledge_assertion",
  "negated": "False",
  "primary_knowledge_source": "infores:drugbank",
  "relation_label": "drug_interaction",
  "subject": "DRUGBANK:DB00393",
  "source_predicate": "DRUGBANK:drug-interaction",
  "agent_type": "manual_agent",
  "predicate": "biolink:interacts_with",
  "domain_range_exclusion": "False",
  "publications_info": "{'sentence': 'The risk or severity of QTc prolongation can be increased when Farnesyl thiopyrophosphate is combined with Nimodipine.'}",
  "predicate_label": "drug-interaction",
  "id": "DRUGBANK:DB00393---DRUGBANK:drug-interaction---None---None---None---DRUGBANK:DB04695---identifiers_org_registry:drugbank",
  "object": "DRUGBANK:DB04695"
}
```

**Comment by saramsey** [comment]
Currently, we seem to be handling this source relation appropriately:
```
DRUGBANK:drug-interaction:
  operation: keep
  core_predicate: biolink:interacts_with
```
Biolink still seems to have the wrong mapping:
```
  physically interacts with:
    is_a: interacts with
    description: >-
      holds between two entities that make physical contact as part of some interaction.
      does not imply a causal relationship.
    in_subset:
      - translator_minimal
    symmetric: true
    annotations:
      canonical_predicate: true
    broad_mappings:
      - WIKIDATA_PROPERTY:P129
    close_mappings:
      - CHEMBL.MECHANISM:binding_agent
      - CHEMBL.MECHANISM:chelating_agent
      - CHEMBL.MECHANISM:cross-linking_agent
      - CHEMBL.MECHANISM:oxidative_enzyme
      - CHEMBL.MECHANISM:sequestering_agent
      - CHEMBL.MECHANISM:substrate
      - DRUGBANK:target
    narrow_mappings:
       # Defined more narrowly as "substance interaction", thus specific applies to a subclass entities
      - DRUGBANK:drug-interaction
      - FMA:adheres_to
      - NCIT:A7
      - PR:non-covalently_bound_to
    mixins:
      - interacts with
```
