### ISSUE TITLE
KG2 listed as ingesting deprecated infores:biothings-multiomics-clinicaltrials

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX-KG2#414]
Gwenlyn pointed out to me today that KG2 is listed as ingesting the **old** biothings-hosted multiomics clinical trials KP (`infores:biothings-multiomics-clinicaltrials`) on this page:

https://github.com/biolink/information-resource-registry/blob/c6e487bb035fb1b0cda8df7e92bb005729a007cd/src/information_resource_registry/relation-map/data/consume_info.csv#L82

that's incorrect, right? KG2.10.1 ingests infores:multiomics-clinicaltrials, I believe...?

**Comment by amykglen** [comment]
this appears to come from the infores_catalog.yaml (thanks again to Gwenlyn for pointing this out):

https://github.com/biolink/information-resource-registry/blob/c6e487bb035fb1b0cda8df7e92bb005729a007cd/infores_catalog.yaml#L950-L958

```
  - id: infores:biothings-multiomics-clinicaltrials
    status: deprecated
    name: Multiomics ClinicalTrials KP API
    xref:
      - https://github.com/NCATSTranslator/Translator-All/wiki/Clinical-Trials-KP
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
    consumed_by:
      - infores:rtx-kg2
```
