### ISSUE TITLE
many qualifiers in predicate-remap.yaml are missing object_aspect or object_direction

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#437]
See 
```
DGIdb:allosteric_modulator:
  operation: keep
  core_predicate: biolink:affects
  qualified_predicate: biolink:causes
  qualifiers:
    object_aspect: activity
```
and many other examples

**Comment by saramsey** [comment]
and this example:
```
DrugCentral:negative_allosteric_modulator:
  operation: keep
  core_predicate: biolink:affects
  qualified_predicate: biolink:causes
  qualifiers:
    object_direction: decreased
```
